version: '3.8'
services:
  db_dotnet:
    image: postgres:18-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_dotnet
    ports:
      - "5432:5432"
    volumes:
      - pgdata_dotnet:/var/lib/postgresql/data

volumes:
  pgdata_dotnet: